
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rollout-demo1
  labels:
    cluster: cluster-a
spec:
  podManagementPolicy: Parallel
  serviceName: rollout-demo1
  replicas: 5
  selector:
    matchLabels:
      cluster: cluster-a
      app: rollout-demo
  template:
    metadata:
      labels:
        cluster: cluster-a
        app: rollout-demo
    spec:
      containers:
      - name: nginxdemo
        image: nginxdemos/hello:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: "tcp-80"
          containerPort: 80
          protocol: TCP
