apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rollout-demo2
  labels:
    cluster: cluster-b
spec:
  podManagementPolicy: Parallel
  serviceName: rollout-demo2
  replicas: 5
  selector:
    matchLabels:
      cluster: cluster-b
  template:
    metadata:
      labels:
        cluster: cluster-b
        pod.rollout.kusionstack.io/revision: base
    spec:
      containers:
      - name: nginxdemo
        image: nginxdemos/hello:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: "tcp-80"
          containerPort: 80
          protocol: TCP
