apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

labels:
  - pairs:
      app: rollout-demo
    includeSelectors: true
    includeTemplates: true

resources:
  - demo1.yaml
  - demo2.yaml
  - rollout.yaml
