
apiVersion: rollout.kusionstack.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-demo
spec:
  strategyRef: rollout-demo
  workloadRef:
    apiVersion: apps/v1
    kind: StatefulSet
    match:
      selector:
        matchLabels:
          app: rollout-demo
  trafficTopologyRefs:
  - rollout-demo1
  - rollout-demo2

---

apiVersion: rollout.kusionstack.io/v1alpha1
kind: RolloutStrategy
metadata:
  name: rollout-demo
canary:
  replicas: 2
  podTemplateMetadataPatch:
    labels:
      service.tag: "canary"
  traffic:
    http:
      filter:
        requestHeaderModifier:
          set:
          - name: x-mse-tag
            value: canary
      matches:
      - headers:
        - type: Exact 
          name: env
          value: canary
batch:
  batches:
  - replicas: 1
  - replicas: 3
    breakpoint: true
  - replicas: 100%
