
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rollout-demo1
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 5
  template:
    metadata:
      annotations:
        version: v2
