apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../bases

patches:
  - path: demo1-v2.yaml
  - path: demo2-v2.yaml

images:
- name: nginxdemos/hello
  newTag: "0.4"
