apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manifests.yaml
- service.yaml

namespace: kusionstack-rollout

patches:
# change validating and mutating webhook configuration name
- patch: |-
    - op: replace
      path: /metadata/name
      value: kusionstack-rollout-validating
  target:
    kind: ValidatingWebhookConfiguration
    name: validating-webhook-configuration
- patch: |-
    - op: replace
      path: /metadata/name
      value: kusionstack-rollout-mutating
  target:
    kind: MutatingWebhookConfiguration
    name: mutating-webhook-configuration
# change service name to kusionstack-rollout-webhook
- patch: |-
    - op: replace
      path: /metadata/name
      value: kusionstack-rollout-webhook-service
  target:
    kind: Service
# set namespaceSelector to only match namespaces without the label webhook.rollout.kusionstack.io/disabled
- patch: |-
    - op: replace
      path: /webhooks/0/namespaceSelector
      value: {"matchExpressions":[{"key":"webhook.rollout.kusionstack.io/disabled","operator":"DoesNotExist"},{"key":"kubernetes.io/metadata.name","operator":"NotIn","values":["kube-node-lease","kube-public","kube-system","kusionstack-system","kusionstack-rollout"]}]}
  target:
    kind: ValidatingWebhookConfiguration


replacements:
# replace service name and namespace and port in webhook configuration
- source:
    kind: Service
    fieldPath: metadata.name
  targets:
  - select:
      kind: ValidatingWebhookConfiguration
    fieldPaths:
    - webhooks.*.clientConfig.service.name
  - select:
      kind: MutatingWebhookConfiguration
    fieldPaths:
    - webhooks.*.clientConfig.service.name
- source:
    kind: Service
    fieldPath: metadata.namespace
  targets:
  - select:
      kind: ValidatingWebhookConfiguration
    fieldPaths:
    - webhooks.*.clientConfig.service.namespace
  - select:
      kind: MutatingWebhookConfiguration
    fieldPaths:
    - webhooks.*.clientConfig.service.namespace
# replace namespaceSelector in webhook configuration
- source:
    kind: ValidatingWebhookConfiguration
    name: validating-webhook-configuration
    fieldPath: webhooks.0.namespaceSelector
  targets:
  - select:
      kind: ValidatingWebhookConfiguration
    fieldPaths:
    - webhooks.*.namespaceSelector
    options:
      create: true
  - select:
      kind: MutatingWebhookConfiguration
    fieldPaths:
    - webhooks.*.namespaceSelector
    options:
      create: true

