
apiVersion: v1
kind: Service
metadata:
  name: webhook-service
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
      name: webhook-443
    - port: 9443
      protocol: TCP
      targetPort: 9443
      name: webhook-9443
  selector:
    app.kubernetes.io/name: kusionstack-rollout-controller
