apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../webhook

patches:
- patch: |-
    - op: replace
      path: /webhooks/0/clientConfig
      value: {"url": "https://host.docker.internal:9443/webhooks/validating/rolloutrun"}
    - op: replace
      path: /webhooks/1/clientConfig
      value: {"url": "https://host.docker.internal:9443/webhooks/validating/rollout"}
    - op: replace
      path: /webhooks/2/clientConfig
      value: {"url": "https://host.docker.internal:9443/webhooks/validating/rolloutstrategy"}
    - op: replace
      path: /webhooks/3/clientConfig
      value: {"url": "https://host.docker.internal:9443/webhooks/validating/traffictopology"}
  target:
    kind: ValidatingWebhookConfiguration
- path: delete-svc.yaml
- path: delete-mutating.yaml


