apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../webhook

patches:
- path: patches/service.yaml
- path: patches/webhook.yaml

replacements:
- source:
    kind: Service
    fieldPath: spec.ports.1.port
  targets:
  - select:
      kind: ValidatingWebhookConfiguration
    fieldPaths:
    - webhooks.*.clientConfig.service.port
    options:
      create: true
  - select:
      kind: MutatingWebhookConfiguration
    fieldPaths:
    - webhooks.*.clientConfig.service.port
    options:
      create: true
