apiVersion: rollout.kusionstack.io/v1alpha1
kind: RolloutStrategy
metadata:
  name: sample
  namespace: default
spec:
  action: Upgrade
  upgradeStrategy:
    canary:
      batchTemplate:
        fixedBatchPolicy:
          batchCount: 5
          betaBatch:
            replicasPerUnit: 1
          breakpoints:
            - 1
            - 3
            - 4
      pauseMode: FirstBatch
      tolerationPolicy:
        failureThreshold: 10%
        waitTimeSeconds: 300