
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rollout.kusionstack.io
  resources:
  - backendroutings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rollout.kusionstack.io
  resources:
  - backendroutings/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - rollout.kusionstack.io
  resources:
  - backendroutings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rollout.kusionstack.io
  resources:
  - rolloutruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rollout.kusionstack.io
  resources:
  - rolloutruns/finalizers
  verbs:
  - update
- apiGroups:
  - rollout.kusionstack.io
  resources:
  - rolloutruns/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rollout.kusionstack.io
  resources:
  - rollouts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rollout.kusionstack.io
  resources:
  - rollouts/finalizers
  verbs:
  - update
- apiGroups:
  - rollout.kusionstack.io
  resources:
  - rollouts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rollout.kusionstack.io
  resources:
  - rolloutstrategies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rollout.kusionstack.io
  resources:
  - traffictopologies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rollout.kusionstack.io
  resources:
  - traffictopologies/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - rollout.kusionstack.io
  resources:
  - traffictopologies/status
  verbs:
  - get
  - patch
  - update
