# permissions for end users to view workflows.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: workflow-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: rollout
    app.kubernetes.io/part-of: rollout
    app.kubernetes.io/managed-by: kustomize
  name: workflow-viewer-role
rules:
- apiGroups:
  - rollout.kusionstack.io
  resources:
  - workflows
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rollout.kusionstack.io
  resources:
  - workflows/status
  verbs:
  - get
