apiVersion: rollout.kusionstack.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app.kubernetes.io/name: rollout
    app.kubernetes.io/instance: rollout-sample
    app.kubernetes.io/part-of: rollout
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: rollout
  name: rollout-sample
spec:

