apiVersion: rollout.kusionstack.io/v1alpha1
kind: Workflow
metadata:
  labels:
    app.kubernetes.io/name: workflow
    app.kubernetes.io/instance: workflow-sample
    app.kubernetes.io/part-of: rollout
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: rollout
  name: workflow-sample
spec:
  # status: Pending
  tasks:
    - name: task1
      taskSpec:
        status: Paused
        echo:
          message: "hello from task1"
